import type { WordCard } from '../types'

// 雅思 + 六级高频词库，按频率分层
export const WORDS: Omit<WordCard, 'easiness' | 'interval' | 'repetitions' | 'nextReview' | 'learned' | 'createdAt'>[] = [
  // === Band 1: 基础核心（四级过渡六级）===
  { word: "abandon", phonetic: "/əˈbændən/", meaning: "v. 放弃；抛弃", example: "They had to abandon the sinking ship.", pos: "v" },
  { word: "absorb", phonetic: "/əbˈzɔːrb/", meaning: "v. 吸收；吸引注意力", example: "Plants absorb nutrients from the soil.", pos: "v" },
  { word: "abstract", phonetic: "/ˈæbstrækt/", meaning: "adj. 抽象的；n. 摘要", example: "The concept is too abstract to understand easily.", pos: "adj" },
  { word: "abundant", phonetic: "/əˈbʌndənt/", meaning: "adj. 丰富的；充裕的", example: "The region has abundant natural resources.", pos: "adj" },
  { word: "academic", phonetic: "/ˌækəˈdemɪk/", meaning: "adj. 学术的；学院的", example: "She has a strong academic background.", pos: "adj" },
  { word: "accelerate", phonetic: "/əkˈseləreɪt/", meaning: "v. 加速；促进", example: "They plan to accelerate the development process.", pos: "v" },
  { word: "accommodate", phonetic: "/əˈkɒmədeɪt/", meaning: "v. 容纳；提供住宿", example: "The hotel can accommodate 500 guests.", pos: "v" },
  { word: "accompany", phonetic: "/əˈkʌmpəni/", meaning: "v. 陪伴；伴随", example: "She will accompany me to the meeting.", pos: "v" },
  { word: "accumulate", phonetic: "/əˈkjuːmjəleɪt/", meaning: "v. 积累；积聚", example: "Wealth tends to accumulate over time.", pos: "v" },
  { word: "accurate", phonetic: "/ˈækjərət/", meaning: "adj. 准确的；精确的", example: "The data needs to be accurate.", pos: "adj" },
  { word: "acknowledge", phonetic: "/əkˈnɒlɪdʒ/", meaning: "v. 承认；确认收到", example: "He refused to acknowledge the mistake.", pos: "v" },
  { word: "acquire", phonetic: "/əˈkwaɪər/", meaning: "v. 获得；习得", example: "It takes time to acquire new skills.", pos: "v" },
  { word: "adapt", phonetic: "/əˈdæpt/", meaning: "v. 适应；改编", example: "Animals adapt to their environment.", pos: "v" },
  { word: "adequate", phonetic: "/ˈædɪkwət/", meaning: "adj. 足够的；适当的", example: "The supply is adequate for our needs.", pos: "adj" },
  { word: "adjust", phonetic: "/əˈdʒʌst/", meaning: "v. 调整；适应", example: "You need to adjust your expectations.", pos: "v" },
  { word: "adolescent", phonetic: "/ˌædəˈlesnt/", meaning: "n. 青少年；adj. 青春期的", example: "The program targets adolescent health issues.", pos: "n" },
  { word: "adopt", phonetic: "/əˈdɒpt/", meaning: "v. 采用；收养", example: "The company decided to adopt new technology.", pos: "v" },
  { word: "advocate", phonetic: "/ˈædvəkeɪt/", meaning: "v. 提倡；n. 倡导者", example: "He advocates for better education policies.", pos: "v" },
  { word: "aggressive", phonetic: "/əˈɡresɪv/", meaning: "adj. 侵略的；好斗的", example: "The company adopted an aggressive marketing strategy.", pos: "adj" },
  { word: "allocate", phonetic: "/ˈæləkeɪt/", meaning: "v. 分配；拨出", example: "Funds are allocated to each department.", pos: "v" },
  { word: "alternative", phonetic: "/ɔːlˈtɜːrnətɪv/", meaning: "n. 替代品；adj. 替代的", example: "We need to find an alternative solution.", pos: "n" },
  { word: "ambiguous", phonetic: "/æmˈbɪɡjuəs/", meaning: "adj. 含糊的；模棱两可的", example: "The statement was intentionally ambiguous.", pos: "adj" },
  { word: "ambitious", phonetic: "/æmˈbɪʃəs/", meaning: "adj. 有雄心的", example: "She is an ambitious young professional.", pos: "adj" },
  { word: "analogy", phonetic: "/əˈnælədʒi/", meaning: "n. 类比；相似", example: "He drew an analogy between the two systems.", pos: "n" },
  { word: "anticipate", phonetic: "/ænˈtɪsɪpeɪt/", meaning: "v. 预期；预见", example: "We anticipate a rise in demand next quarter.", pos: "v" },
  { word: "apparent", phonetic: "/əˈpærənt/", meaning: "adj. 明显的；表面上的", example: "The reason became apparent after analysis.", pos: "adj" },
  { word: "approach", phonetic: "/əˈprəʊtʃ/", meaning: "n. 方法；v. 接近", example: "We need a new approach to this problem.", pos: "n" },
  { word: "appropriate", phonetic: "/əˈprəʊpriət/", meaning: "adj. 合适的；恰当的", example: "This is not the appropriate time to discuss it.", pos: "adj" },
  { word: "approximate", phonetic: "/əˈprɒksɪmət/", meaning: "adj. 大约的；近似的", example: "The approximate cost is $500.", pos: "adj" },
  { word: "arbitrary", phonetic: "/ˈɑːrbɪtrəri/", meaning: "adj. 任意的；武断的", example: "The decision seemed completely arbitrary.", pos: "adj" },
  { word: "assess", phonetic: "/əˈses/", meaning: "v. 评估；评定", example: "We need to assess the impact of the change.", pos: "v" },
  { word: "assign", phonetic: "/əˈsaɪn/", meaning: "v. 分配；指派", example: "The task was assigned to the new team.", pos: "v" },
  { word: "assume", phonetic: "/əˈsjuːm/", meaning: "v. 假设；承担", example: "Let's assume the data is correct.", pos: "v" },
  { word: "attain", phonetic: "/əˈteɪn/", meaning: "v. 达到；获得", example: "She worked hard to attain her goals.", pos: "v" },
  { word: "attribute", phonetic: "/ˈætrɪbjuːt/", meaning: "v. 归因于；n. 属性", example: "They attribute their success to teamwork.", pos: "v" },
  { word: "authority", phonetic: "/ɔːˈθɒrəti/", meaning: "n. 权威；当局", example: "He is an authority on ancient history.", pos: "n" },
  { word: "automatic", phonetic: "/ˌɔːtəˈmætɪk/", meaning: "adj. 自动的；无意识的", example: "The system runs on automatic mode.", pos: "adj" },
  { word: "barrier", phonetic: "/ˈbæriər/", meaning: "n. 障碍；壁垒", example: "Language can be a barrier to communication.", pos: "n" },
  { word: "bonus", phonetic: "/ˈbəʊnəs/", meaning: "n. 奖金；额外好处", example: "Employees receive an annual bonus.", pos: "n" },
  { word: "budget", phonetic: "/ˈbʌdʒɪt/", meaning: "n. 预算；v. 做预算", example: "We need to stay within the budget.", pos: "n" },
  { word: "bulk", phonetic: "/bʌlk/", meaning: "n. 大量；大部分", example: "The bulk of the work is already done.", pos: "n" },
  { word: "capable", phonetic: "/ˈkeɪpəbl/", meaning: "adj. 有能力的", example: "She is a capable and experienced leader.", pos: "adj" },
  { word: "category", phonetic: "/ˈkætəɡəri/", meaning: "n. 类别；范畴", example: "These products fall into a different category.", pos: "n" },
  { word: "cease", phonetic: "/siːs/", meaning: "v. 停止；终止", example: "The company will cease operations next month.", pos: "v" },
  { word: "challenge", phonetic: "/ˈtʃælɪndʒ/", meaning: "n. 挑战；v. 质疑", example: "This project presents a significant challenge.", pos: "n" },
  { word: "circumstance", phonetic: "/ˈsɜːrkəmstæns/", meaning: "n. 环境；情况", example: "Under normal circumstances, this would work.", pos: "n" },
  { word: "collapse", phonetic: "/kəˈlæps/", meaning: "v. 崩溃；倒塌", example: "The building collapsed during the earthquake.", pos: "v" },
  { word: "commence", phonetic: "/kəˈmens/", meaning: "v. 开始；着手", example: "The meeting will commence at 9 AM.", pos: "v" },
  { word: "commitment", phonetic: "/kəˈmɪtmənt/", meaning: "n. 承诺；奉献", example: "This job requires a long-term commitment.", pos: "n" },
  { word: "community", phonetic: "/kəˈmjuːnəti/", meaning: "n. 社区；团体", example: "The local community supports this initiative.", pos: "n" },

  // === Band 2: 六级核心 ===
  { word: "compatible", phonetic: "/kəmˈpætəbl/", meaning: "adj. 兼容的；一致的", example: "The software is compatible with most devices.", pos: "adj" },
  { word: "compensate", phonetic: "/ˈkɒmpenseɪt/", meaning: "v. 补偿；赔偿", example: "The company promised to compensate affected customers.", pos: "v" },
  { word: "compile", phonetic: "/kəmˈpaɪl/", meaning: "v. 编译；汇编", example: "The report compiles data from various sources.", pos: "v" },
  { word: "complement", phonetic: "/ˈkɒmplɪment/", meaning: "v. 补充；n. 补充物", example: "The two skills complement each other well.", pos: "v" },
  { word: "complex", phonetic: "/ˈkɒmpleks/", meaning: "adj. 复杂的；n. 综合体", example: "The problem is more complex than it appears.", pos: "adj" },
  { word: "component", phonetic: "/kəmˈpəʊnənt/", meaning: "n. 组成部分；组件", example: "Each component plays a vital role.", pos: "n" },
  { word: "comprehensive", phonetic: "/ˌkɒmprɪˈhensɪv/", meaning: "adj. 综合的；全面的", example: "We offer a comprehensive range of services.", pos: "adj" },
  { word: "comprise", phonetic: "/kəmˈpraɪz/", meaning: "v. 包括；由…组成", example: "The team comprises five experts.", pos: "v" },
  { word: "conceive", phonetic: "/kənˈsiːv/", meaning: "v. 构想；设想", example: "It's difficult to conceive such a large scale.", pos: "v" },
  { word: "concentrate", phonetic: "/ˈkɒnsntreɪt/", meaning: "v. 集中；专注", example: "I need to concentrate on this task.", pos: "v" },
  { word: "concept", phonetic: "/ˈkɒnsept/", meaning: "n. 概念；观念", example: "The concept of time varies across cultures.", pos: "n" },
  { word: "conclude", phonetic: "/kənˈkluːd/", meaning: "v. 得出结论；结束", example: "What can we conclude from this data?", pos: "v" },
  { word: "conduct", phonetic: "/kənˈdʌkt/", meaning: "v. 进行；指挥", example: "They will conduct a survey next week.", pos: "v" },
  { word: "conference", phonetic: "/ˈkɒnfərəns/", meaning: "n. 会议；研讨会", example: "She presented her paper at the conference.", pos: "n" },
  { word: "confirm", phonetic: "/kənˈfɜːrm/", meaning: "v. 确认；证实", example: "Can you confirm the meeting time?", pos: "v" },
  { word: "conflict", phonetic: "/ˈkɒnflɪkt/", meaning: "n. 冲突；v. 矛盾", example: "There is a conflict of interest here.", pos: "n" },
  { word: "conscious", phonetic: "/ˈkɒnʃəs/", meaning: "adj. 有意识的；清醒的", example: "We need to be conscious of our impact.", pos: "adj" },
  { word: "consequence", phonetic: "/ˈkɒnsɪkwəns/", meaning: "n. 结果；后果", example: "Every action has its consequences.", pos: "n" },
  { word: "considerable", phonetic: "/kənˈsɪdərəbl/", meaning: "adj. 相当大的；可观的", example: "A considerable amount of work remains.", pos: "adj" },
  { word: "consistent", phonetic: "/kənˈsɪstənt/", meaning: "adj. 一致的；始终如一的", example: "Her performance has been consistently excellent.", pos: "adj" },
  { word: "constant", phonetic: "/ˈkɒnstənt/", meaning: "adj. 持续的；不变的", example: "The city is in constant motion.", pos: "adj" },
  { word: "constitute", phonetic: "/ˈkɒnstɪtjuːt/", meaning: "v. 构成；组成", example: "Women constitute 60% of the workforce.", pos: "v" },
  { word: "constrain", phonetic: "/kənˈstreɪn/", meaning: "v. 限制；约束", example: "Budget cuts constrain our options.", pos: "v" },
  { word: "construct", phonetic: "/kənˈstrʌkt/", meaning: "v. 建造；构建", example: "They plan to construct a new bridge.", pos: "v" },
  { word: "consume", phonetic: "/kənˈsjuːm/", meaning: "v. 消费；消耗", example: "This process consumes a lot of energy.", pos: "v" },
  { word: "contemporary", phonetic: "/kənˈtempərəri/", meaning: "adj. 当代的；同时代的", example: "Contemporary art often challenges tradition.", pos: "adj" },
  { word: "contract", phonetic: "/ˈkɒntrækt/", meaning: "n. 合同；v. 收缩", example: "Both parties signed the contract.", pos: "n" },
  { word: "contribute", phonetic: "/kənˈtrɪbjuːt/", meaning: "v. 贡献；促成", example: "Everyone should contribute to the team.", pos: "v" },
  { word: "controversy", phonetic: "/ˈkɒntrəvɜːrsi/", meaning: "n. 争议；争论", example: "The policy sparked widespread controversy.", pos: "n" },
  { word: "convention", phonetic: "/kənˈvenʃn/", meaning: "n. 习俗；惯例；大会", example: "It's a social convention to shake hands.", pos: "n" },
  { word: "convince", phonetic: "/kənˈvɪns/", meaning: "v. 说服；使确信", example: "He failed to convince the investors.", pos: "v" },
  { word: "cooperate", phonetic: "/kəʊˈɒpəreɪt/", meaning: "v. 合作；配合", example: "The two companies agreed to cooperate.", pos: "v" },
  { word: "coordinate", phonetic: "/kəʊˈɔːrdɪneɪt/", meaning: "v. 协调；配合", example: "We need to coordinate our efforts.", pos: "v" },
  { word: "corporate", phonetic: "/ˈkɔːrpərət/", meaning: "adj. 公司的；法人的", example: "Corporate culture varies between companies.", pos: "adj" },
  { word: "correspond", phonetic: "/ˌkɒrəˈspɒnd/", meaning: "v. 相符；通信", example: "The results correspond to our predictions.", pos: "v" },
  { word: "crucial", phonetic: "/ˈkruːʃl/", meaning: "adj. 关键的；决定性的", example: "This decision is crucial for our future.", pos: "adj" },
  { word: "currency", phonetic: "/ˈkʌrənsi/", meaning: "n. 货币；通用", example: "The local currency has depreciated.", pos: "n" },
  { word: "decline", phonetic: "/dɪˈklaɪn/", meaning: "v. 下降；拒绝", example: "Sales declined by 15% this quarter.", pos: "v" },
  { word: "dedicate", phonetic: "/ˈdedɪkeɪt/", meaning: "v. 奉献；致力于", example: "She dedicated her life to education.", pos: "v" },
  { word: "definite", phonetic: "/ˈdefɪnət/", meaning: "adj. 明确的；肯定的", example: "We need a definite answer by Friday.", pos: "adj" },
  { word: "demonstrate", phonetic: "/ˈdemənstreɪt/", meaning: "v. 展示；证明", example: "Let me demonstrate how this works.", pos: "v" },
  { word: "deny", phonetic: "/dɪˈnaɪ/", meaning: "v. 否认；拒绝", example: "The company denied any wrongdoing.", pos: "v" },
  { word: "depict", phonetic: "/dɪˈpɪkt/", meaning: "v. 描绘；描述", example: "The painting depicts a rural landscape.", pos: "v" },
  { word: "derive", phonetic: "/dɪˈraɪv/", meaning: "v. 源自；导出", example: "The word derives from Latin.", pos: "v" },
  { word: "despite", phonetic: "/dɪˈspaɪt/", meaning: "prep. 尽管；不管", example: "Despite the rain, the game continued.", pos: "prep" },
  { word: "detect", phonetic: "/dɪˈtekt/", meaning: "v. 检测；察觉", example: "The system can detect early warning signs.", pos: "v" },
  { word: "device", phonetic: "/dɪˈvaɪs/", meaning: "n. 设备；装置", example: "This device can monitor your heart rate.", pos: "n" },
  { word: "devote", phonetic: "/dɪˈvəʊt/", meaning: "v. 致力于；奉献", example: "He devotes hours to practice each day.", pos: "v" },
  { word: "dimension", phonetic: "/daɪˈmenʃn/", meaning: "n. 维度；尺寸", example: "We need to consider the social dimension.", pos: "n" },
  { word: "diminish", phonetic: "/dɪˈmɪnɪʃ/", meaning: "v. 减少；削弱", example: "The pain gradually diminished.", pos: "v" },
  { word: "discipline", phonetic: "/ˈdɪsəplɪn/", meaning: "n. 纪律；学科", example: "Self-discipline is key to success.", pos: "n" },
  { word: "discriminate", phonetic: "/dɪˈskrɪmɪneɪt/", meaning: "v. 歧视；区分", example: "The law prohibits employers from discriminating.", pos: "v" },
  { word: "dispose", phonetic: "/dɪˈspəʊz/", meaning: "v. 处理；处置", example: "How should we dispose of hazardous waste?", pos: "v" },
  { word: "distinct", phonetic: "/dɪˈstɪŋkt/", meaning: "adj. 不同的；明显的", example: "Each culture has its own distinct identity.", pos: "adj" },
  { word: "distinguish", phonetic: "/dɪˈstɪŋɡwɪʃ/", meaning: "v. 区分；辨别", example: "It's hard to distinguish fact from opinion.", pos: "v" },
  { word: "distribute", phonetic: "/dɪˈstrɪbjuːt/", meaning: "v. 分配；分发", example: "The organization distributes food to the poor.", pos: "v" },
  { word: "diverse", phonetic: "/daɪˈvɜːrs/", meaning: "adj. 多样的；不同的", example: "The city has a diverse population.", pos: "adj" },
  { word: "document", phonetic: "/ˈdɒkjumənt/", meaning: "n. 文件；v. 记录", example: "Please sign the document at the bottom.", pos: "n" },
  { word: "domestic", phonetic: "/dəˈmestɪk/", meaning: "adj. 国内的；家庭的", example: "Domestic demand has been growing steadily.", pos: "adj" },
  { word: "dominate", phonetic: "/ˈdɒmɪneɪt/", meaning: "v. 支配；主导", example: "The company dominates the market.", pos: "v" },
  { word: "draft", phonetic: "/drɑːft/", meaning: "n. 草稿；v. 起草", example: "Here is the first draft of the report.", pos: "n" },
  { word: "dynamic", phonetic: "/daɪˈnæmɪk/", meaning: "adj. 动态的；充满活力的", example: "The market is highly dynamic.", pos: "adj" },
  { word: "elaborate", phonetic: "/ɪˈlæbərət/", meaning: "v. 详细阐述；adj. 精心制作的", example: "Could you elaborate on that point?", pos: "v" },
  { word: "eliminate", phonetic: "/ɪˈlɪmɪneɪt/", meaning: "v. 消除；淘汰", example: "We need to eliminate unnecessary costs.", pos: "v" },
  { word: "emerge", phonetic: "/ɪˈmɜːrdʒ/", meaning: "v. 出现；浮现", example: "A new trend is emerging in the industry.", pos: "v" },
  { word: "emphasis", phonetic: "/ˈemfəsɪs/", meaning: "n. 重点；强调", example: "The course places emphasis on practical skills.", pos: "n" },
  { word: "empirical", phonetic: "/ɪmˈpɪrɪkl/", meaning: "adj. 经验的；实证的", example: "We need empirical evidence to support this claim.", pos: "adj" },
  { word: "enable", phonetic: "/ɪˈneɪbl/", meaning: "v. 使能够；启用", example: "Technology enables remote work.", pos: "v" },
  { word: "encounter", phonetic: "/ɪnˈkaʊntər/", meaning: "v. 遇到；遭遇", example: "We encountered some unexpected problems.", pos: "v" },
  { word: "enormous", phonetic: "/ɪˈnɔːrməs/", meaning: "adj. 巨大的；庞大的", example: "The project requires enormous resources.", pos: "adj" },
  { word: "ensure", phonetic: "/ɪnˈʃʊr/", meaning: "v. 确保；保证", example: "Please ensure all files are saved.", pos: "v" },
  { word: "entity", phonetic: "/ˈentəti/", meaning: "n. 实体；独立存在物", example: "The company is a separate legal entity.", pos: "n" },
  { word: "environment", phonetic: "/ɪnˈvaɪrənmənt/", meaning: "n. 环境", example: "We must protect the environment.", pos: "n" },
  { word: "equivalent", phonetic: "/ɪˈkwɪvələnt/", meaning: "adj. 等同的；n. 等价物", example: "One mile is equivalent to 1.6 kilometers.", pos: "adj" },
  { word: "establish", phonetic: "/ɪˈstæblɪʃ/", meaning: "v. 建立；设立", example: "The company was established in 1990.", pos: "v" },
  { word: "estate", phonetic: "/ɪˈsteɪt/", meaning: "n. 房产；遗产", example: "The estate includes several buildings.", pos: "n" },
  { word: "evaluate", phonetic: "/ɪˈvæljueɪt/", meaning: "v. 评估；评价", example: "We evaluate employees twice a year.", pos: "v" },
  { word: "evidence", phonetic: "/ˈevɪdəns/", meaning: "n. 证据；迹象", example: "There is clear evidence of climate change.", pos: "n" },
  { word: "evolve", phonetic: "/ɪˈvɒlv/", meaning: "v. 进化；发展", example: "Technology continues to evolve rapidly.", pos: "v" },
  { word: "exceed", phonetic: "/ɪkˈsiːd/", meaning: "v. 超过；超出", example: "Costs exceeded the original budget.", pos: "v" },
  { word: "exclude", phonetic: "/ɪkˈskluːd/", meaning: "v. 排除；不包括", example: "The price excludes tax.", pos: "v" },
  { word: "exhibit", phonetic: "/ɪɡˈzɪbɪt/", meaning: "v. 展示；展出", example: "The artist will exhibit her work in June.", pos: "v" },
  { word: "expand", phonetic: "/ɪkˈspænd/", meaning: "v. 扩展；膨胀", example: "The company plans to expand overseas.", pos: "v" },
  { word: "expertise", phonetic: "/ˌekspɜːrˈtiːz/", meaning: "n. 专长；专业知识", example: "She has expertise in data analysis.", pos: "n" },
  { word: "exploit", phonetic: "/ɪkˈsplɔɪt/", meaning: "v. 利用；开发", example: "We should exploit this opportunity fully.", pos: "v" },
  { word: "expose", phonetic: "/ɪkˈspəʊz/", meaning: "v. 暴露；揭露", example: "The report exposes serious flaws in the system.", pos: "v" },
  { word: "external", phonetic: "/ɪkˈstɜːrnl/", meaning: "adj. 外部的；外界的", example: "External factors affect our performance.", pos: "adj" },
  { word: "extract", phonetic: "/ɪkˈstrækt/", meaning: "v. 提取；摘录", example: "We can extract useful data from these reports.", pos: "v" },
  { word: "facilitate", phonetic: "/fəˈsɪlɪteɪt/", meaning: "v. 促进；便利", example: "Good communication facilitates collaboration.", pos: "v" },
  { word: "feature", phonetic: "/ˈfiːtʃər/", meaning: "n. 特征；特点", example: "What are the key features of this product?", pos: "n" },
  { word: "finance", phonetic: "/ˈfaɪnæns/", meaning: "n. 金融；v. 资助", example: "The project needs additional finance.", pos: "n" },
  { word: "flexible", phonetic: "/ˈfleksəbl/", meaning: "adj. 灵活的；弹性的", example: "We offer flexible working hours.", pos: "adj" },
  { word: "fluctuate", phonetic: "/ˈflʌktʃueɪt/", meaning: "v. 波动；变动", example: "Prices fluctuate with supply and demand.", pos: "v" },
  { word: "framework", phonetic: "/ˈfreɪmwɜːrk/", meaning: "n. 框架；结构", example: "The report provides a useful framework for discussion.", pos: "n" },
  { word: "fundamental", phonetic: "/ˌfʌndəˈmentl/", meaning: "adj. 基本的；根本的", example: "This is a fundamental principle of physics.", pos: "adj" },
  { word: "generate", phonetic: "/ˈdʒenəreɪt/", meaning: "v. 产生；生成", example: "The project will generate significant revenue.", pos: "v" },
  { word: "guarantee", phonetic: "/ˌɡærənˈtiː/", meaning: "n. 保证；v. 担保", example: "There is no guarantee of success.", pos: "n" },
  { word: "guideline", phonetic: "/ˈɡaɪdlaɪn/", meaning: "n. 指南；指导方针", example: "Follow the guidelines for submitting reports.", pos: "n" },
  { word: "highlight", phonetic: "/ˈhaɪlaɪt/", meaning: "v. 强调；突出", example: "The report highlights key areas for improvement.", pos: "v" },
  { word: "hypothesis", phonetic: "/haɪˈpɒθəsɪs/", meaning: "n. 假设；假说", example: "We need to test this hypothesis.", pos: "n" },
  { word: "identify", phonetic: "/aɪˈdentɪfaɪ/", meaning: "v. 识别；确认", example: "Can you identify the source of the problem?", pos: "v" },
  { word: "illustrate", phonetic: "/ˈɪləstreɪt/", meaning: "v. 说明；阐明", example: "Let me illustrate this with an example.", pos: "v" },
  { word: "immigrate", phonetic: "/ˈɪmɪɡreɪt/", meaning: "v. 移民（迁入）", example: "Many people immigrate for better opportunities.", pos: "v" },
  { word: "impact", phonetic: "/ˈɪmpækt/", meaning: "n. 影响；冲击", example: "The policy had a significant impact.", pos: "n" },
  { word: "implement", phonetic: "/ˈɪmplɪment/", meaning: "v. 实施；执行", example: "The plan will be implemented next month.", pos: "v" },
  { word: "implicit", phonetic: "/ɪmˈplɪsɪt/", meaning: "adj. 含蓄的；内含的", example: "There was an implicit agreement between them.", pos: "adj" },
  { word: "impose", phonetic: "/ɪmˈpəʊz/", meaning: "v. 强加；征收", example: "The government imposed new taxes.", pos: "v" },
  { word: "incentive", phonetic: "/ɪnˈsentɪv/", meaning: "n. 激励；动力", example: "Bonuses provide a strong incentive to perform.", pos: "n" },
  { word: "incorporate", phonetic: "/ɪnˈkɔːrpəreɪt/", meaning: "v. 纳入；合并", example: "We will incorporate your suggestions.", pos: "v" },
  { word: "indicate", phonetic: "/ˈɪndɪkeɪt/", meaning: "v. 表明；指示", example: "The data indicates a positive trend.", pos: "v" },
  { word: "individual", phonetic: "/ˌɪndɪˈvɪdʒuəl/", meaning: "n. 个人；adj. 个体的", example: "Each individual has unique needs.", pos: "n" },
  { word: "inevitable", phonetic: "/ɪnˈevɪtəbl/", meaning: "adj. 不可避免的", example: "Change is inevitable in any industry.", pos: "adj" },
  { word: "infer", phonetic: "/ɪnˈfɜːr/", meaning: "v. 推断；推论", example: "What can we infer from these results?", pos: "v" },
  { word: "infrastructure", phonetic: "/ˈɪnfrəstrʌktʃər/", meaning: "n. 基础设施", example: "The country needs to invest in infrastructure.", pos: "n" },
  { word: "inhibit", phonetic: "/ɪnˈhɪbɪt/", meaning: "v. 抑制；阻止", example: "Fear can inhibit creativity.", pos: "v" },
  { word: "initial", phonetic: "/ɪˈnɪʃl/", meaning: "adj. 最初的；开始的", example: "The initial results are promising.", pos: "adj" },
  { word: "initiative", phonetic: "/ɪˈnɪʃətɪv/", meaning: "n. 主动性；倡议", example: "She showed great initiative on the project.", pos: "n" },
  { word: "innovate", phonetic: "/ˈɪnəveɪt/", meaning: "v. 创新；革新", example: "Companies must constantly innovate to survive.", pos: "v" },
  { word: "insight", phonetic: "/ˈɪnsaɪt/", meaning: "n. 洞察力；深刻见解", example: "The research provides valuable insights.", pos: "n" },
  { word: "instance", phonetic: "/ˈɪnstəns/", meaning: "n. 实例；情况", example: "In this instance, the rule doesn't apply.", pos: "n" },
  { word: "institute", phonetic: "/ˈɪnstɪtjuːt/", meaning: "n. 机构；学院", example: "The institute conducts medical research.", pos: "n" },
  { word: "integrate", phonetic: "/ˈɪntɪɡreɪt/", meaning: "v. 整合；融入", example: "We need to integrate the new system.", pos: "v" },
  { word: "interact", phonetic: "/ˌɪntərˈækt/", meaning: "v. 互动；相互作用", example: "How do these chemicals interact?", pos: "v" },
  { word: "interpret", phonetic: "/ɪnˈtɜːrprɪt/", meaning: "v. 解释；理解", example: "How should we interpret these findings?", pos: "v" },
  { word: "intervene", phonetic: "/ˌɪntərˈviːn/", meaning: "v. 干预；介入", example: "The government decided to intervene.", pos: "v" },
  { word: "invest", phonetic: "/ɪnˈvest/", meaning: "v. 投资；投入", example: "We should invest more in education.", pos: "v" },
  { word: "isolate", phonetic: "/ˈaɪsəleɪt/", meaning: "v. 隔离；孤立", example: "The village was isolated by heavy snow.", pos: "v" },
  { word: "justify", phonetic: "/ˈdʒʌstɪfaɪ/", meaning: "v. 证明…有理；辩护", example: "How can you justify this decision?", pos: "v" },
  { word: "legislation", phonetic: "/ˌledʒɪsˈleɪʃn/", meaning: "n. 法律；立法", example: "New legislation is being introduced.", pos: "n" },
  { word: "liberal", phonetic: "/ˈlɪbərəl/", meaning: "adj. 自由的；开明的", example: "She has a liberal approach to education.", pos: "adj" },
  { word: "maintain", phonetic: "/meɪnˈteɪn/", meaning: "v. 维持；保养", example: "It's important to maintain good relationships.", pos: "v" },
  { word: "manifest", phonetic: "/ˈmænɪfest/", meaning: "v. 显示；表明", example: "Symptoms typically manifest within days.", pos: "v" },
  { word: "mechanism", phonetic: "/ˈmekənɪzəm/", meaning: "n. 机制；原理", example: "The mechanism behind climate change is well understood.", pos: "n" },
  { word: "medium", phonetic: "/ˈmiːdiəm/", meaning: "n. 媒介；方法", example: "The internet is a powerful medium for communication.", pos: "n" },
  { word: "migrate", phonetic: "/maɪˈɡreɪt/", meaning: "v. 迁移；迁徙", example: "Birds migrate south for the winter.", pos: "v" },
  { word: "minimize", phonetic: "/ˈmɪnɪmaɪz/", meaning: "v. 最小化；减少", example: "We aim to minimize environmental impact.", pos: "v" },
  { word: "modify", phonetic: "/ˈmɒdɪfaɪ/", meaning: "v. 修改；调整", example: "The design was modified based on feedback.", pos: "v" },
  { word: "monitor", phonetic: "/ˈmɒnɪtər/", meaning: "v. 监控；监测", example: "We closely monitor the market trends.", pos: "v" },
  { word: "motivate", phonetic: "/ˈməʊtɪveɪt/", meaning: "v. 激励；驱动", example: "What motivates you to work hard?", pos: "v" },
  { word: "neglect", phonetic: "/nɪˈɡlekt/", meaning: "v. 忽视；疏忽", example: "Don't neglect your health.", pos: "v" },
  { word: "negotiate", phonetic: "/nɪˈɡəʊʃieɪt/", meaning: "v. 谈判；协商", example: "Both sides are willing to negotiate.", pos: "v" },
  { word: "network", phonetic: "/ˈnetwɜːrk/", meaning: "n. 网络；关系网", example: "Building a professional network is essential.", pos: "n" },
  { word: "nevertheless", phonetic: "/ˌnevərðəˈles/", meaning: "adv. 然而；尽管如此", example: "It was risky; nevertheless, they proceeded.", pos: "adv" },
  { word: "notion", phonetic: "/ˈnəʊʃn/", meaning: "n. 概念；想法", example: "I reject the notion that effort doesn't matter.", pos: "n" },
  { word: "obtain", phonetic: "/əbˈteɪn/", meaning: "v. 获得；得到", example: "You need a license to obtain this data.", pos: "v" },
  { word: "occupation", phonetic: "/ˌɒkjuˈpeɪʃn/", meaning: "n. 职业；占领", example: "What is your current occupation?", pos: "n" },
  { word: "oriented", phonetic: "/ˈɔːrientɪd/", meaning: "adj. 导向的；以…为重点的", example: "This is a result-oriented organization.", pos: "adj" },
  { word: "outcome", phonetic: "/ˈaʊtkʌm/", meaning: "n. 结果；成果", example: "We are pleased with the outcome.", pos: "n" },
  { word: "overall", phonetic: "/ˌəʊvərˈɔːl/", meaning: "adj. 总体的；全面的", example: "The overall performance has improved.", pos: "adj" },
  { word: "paradigm", phonetic: "/ˈpærədaɪm/", meaning: "n. 范式；典范", example: "A paradigm shift is needed in this field.", pos: "n" },
  { word: "participate", phonetic: "/pɑːrˈtɪsɪpeɪt/", meaning: "v. 参与；参加", example: "All students should participate in discussions.", pos: "v" },
  { word: "perceive", phonetic: "/pərˈsiːv/", meaning: "v. 感知；理解", example: "How do you perceive the current situation?", pos: "v" },
  { word: "persist", phonetic: "/pərˈsɪst/", meaning: "v. 坚持；持续", example: "If symptoms persist, consult a doctor.", pos: "v" },
  { word: "perspective", phonetic: "/pərˈspektɪv/", meaning: "n. 观点；视角", example: "Try to look at it from a different perspective.", pos: "n" },
  { word: "phenomenon", phonetic: "/fɪˈnɒmɪnən/", meaning: "n. 现象", example: "This is a relatively recent phenomenon.", pos: "n" },
  { word: "policy", phonetic: "/ˈpɒləsi/", meaning: "n. 政策；方针", example: "The new policy takes effect next month.", pos: "n" },
  { word: "potential", phonetic: "/pəˈtenʃl/", meaning: "n. 潜力；adj. 潜在的", example: "She has great potential as a leader.", pos: "n" },
  { word: "precede", phonetic: "/prɪˈsiːd/", meaning: "v. 在…之前；先于", example: "The agreement preceded the actual deal.", pos: "v" },
  { word: "predict", phonetic: "/prɪˈdɪkt/", meaning: "v. 预测；预报", example: "It's difficult to predict the long-term effects.", pos: "v" },
  { word: "predominant", phonetic: "/prɪˈdɒmɪnənt/", meaning: "adj. 主要的；占主导地位的", example: "English is the predominant language of business.", pos: "adj" },
  { word: "preliminary", phonetic: "/prɪˈlɪmɪnəri/", meaning: "adj. 初步的；预备的", example: "The preliminary results are encouraging.", pos: "adj" },
  { word: "presume", phonetic: "/prɪˈzjuːm/", meaning: "v. 假定；推测", example: "I presume you agree with this approach.", pos: "v" },
  { word: "previous", phonetic: "/ˈpriːviəs/", meaning: "adj. 先前的；以前的", example: "This is better than the previous version.", pos: "adj" },
  { word: "principal", phonetic: "/ˈprɪnsəpl/", meaning: "adj. 主要的；n. 校长", example: "The principal reason was lack of funding.", pos: "adj" },
  { word: "principle", phonetic: "/ˈprɪnsəpl/", meaning: "n. 原则；原理", example: "It's against my principles to lie.", pos: "n" },
  { word: "prior", phonetic: "/ˈpraɪər/", meaning: "adj. 以前的；优先的", example: "Prior experience is required for this role.", pos: "adj" },
  { word: "priority", phonetic: "/praɪˈɒrəti/", meaning: "n. 优先；优先事项", example: "Health should be our top priority.", pos: "n" },
  { word: "procedure", phonetic: "/prəˈsiːdʒər/", meaning: "n. 程序；步骤", example: "Follow the standard procedure for reporting.", pos: "n" },
  { word: "promote", phonetic: "/prəˈməʊt/", meaning: "v. 促进；晋升", example: "Exercise promotes good health.", pos: "v" },
  { word: "proportion", phonetic: "/prəˈpɔːrʃn/", meaning: "n. 比例；部分", example: "A large proportion of the budget goes to research.", pos: "n" },
  { word: "prospect", phonetic: "/ˈprɒspekt/", meaning: "n. 前景；可能性", example: "The prospects for economic growth are good.", pos: "n" },
  { word: "pursue", phonetic: "/pərˈsjuː/", meaning: "v. 追求；从事", example: "She decided to pursue a career in medicine.", pos: "v" },
  { word: "quest", phonetic: "/kwest/", meaning: "n. 探索；追求", example: "The quest for knowledge never ends.", pos: "n" },
  { word: "random", phonetic: "/ˈrændəm/", meaning: "adj. 随机的；任意的", example: "A random sample was selected for the survey.", pos: "adj" },
  { word: "range", phonetic: "/reɪndʒ/", meaning: "n. 范围；系列", example: "We offer a wide range of products.", pos: "n" },
  { word: "ratio", phonetic: "/ˈreɪʃiəʊ/", meaning: "n. 比例；比率", example: "The ratio of men to women is roughly equal.", pos: "n" },
  { word: "recover", phonetic: "/rɪˈkʌvər/", meaning: "v. 恢复；康复", example: "The economy is starting to recover.", pos: "v" },
  { word: "regulate", phonetic: "/ˈreɡjuleɪt/", meaning: "v. 调节；管理", example: "The body regulates its own temperature.", pos: "v" },
  { word: "reinforce", phonetic: "/ˌriːɪnˈfɔːrs/", meaning: "v. 加强；巩固", example: "This evidence reinforces our argument.", pos: "v" },
  { word: "reluctant", phonetic: "/rɪˈlʌktənt/", meaning: "adj. 不情愿的；勉强的", example: "He was reluctant to give up control.", pos: "adj" },
  { word: "require", phonetic: "/rɪˈkwaɪər/", meaning: "v. 需要；要求", example: "This task requires careful planning.", pos: "v" },
  { word: "resolve", phonetic: "/rɪˈzɒlv/", meaning: "v. 解决；决定", example: "We need to resolve this issue quickly.", pos: "v" },
  { word: "resource", phonetic: "/rɪˈsɔːrs/", meaning: "n. 资源", example: "Natural resources are finite.", pos: "n" },
  { word: "restore", phonetic: "/rɪˈstɔːr/", meaning: "v. 恢复；修复", example: "Efforts are being made to restore the ecosystem.", pos: "v" },
  { word: "restrict", phonetic: "/rɪˈstrɪkt/", meaning: "v. 限制；约束", example: "Access is restricted to authorized personnel.", pos: "v" },
  { word: "retain", phonetic: "/rɪˈteɪn/", meaning: "v. 保留；保持", example: "It's important to retain skilled employees.", pos: "v" },
  { word: "reveal", phonetic: "/rɪˈviːl/", meaning: "v. 揭示；透露", example: "The investigation revealed serious problems.", pos: "v" },
  { word: "revenue", phonetic: "/ˈrevənjuː/", meaning: "n. 收入；收益", example: "The company's revenue increased by 20%.", pos: "n" },
  { word: "reverse", phonetic: "/rɪˈvɜːrs/", meaning: "v. 逆转；颠倒", example: "The decision was later reversed.", pos: "v" },
  { word: "revolution", phonetic: "/ˌrevəˈluːʃn/", meaning: "n. 革命；巨变", example: "The internet has sparked a digital revolution.", pos: "n" },
  { word: "rigid", phonetic: "/ˈrɪdʒɪd/", meaning: "adj. 僵硬的；严格的", example: "The rules are too rigid.", pos: "adj" },
  { word: "schedule", phonetic: "/ˈʃedjuːl/", meaning: "n. 时间表；v. 安排", example: "The meeting is scheduled for 3 PM.", pos: "n" },
  { word: "scheme", phonetic: "/skiːm/", meaning: "n. 方案；计划", example: "The government launched a new housing scheme.", pos: "n" },
  { word: "scope", phonetic: "/skəʊp/", meaning: "n. 范围；余地", example: "This goes beyond the scope of our project.", pos: "n" },
  { word: "section", phonetic: "/ˈsekʃn/", meaning: "n. 部分；章节", example: "Read the first section of the report.", pos: "n" },
  { word: "security", phonetic: "/sɪˈkjʊərəti/", meaning: "n. 安全；保障", example: "Airport security has been tightened.", pos: "n" },
  { word: "segment", phonetic: "/ˈseɡmənt/", meaning: "n. 部分；段", example: "This market segment is growing rapidly.", pos: "n" },
  { word: "shift", phonetic: "/ʃɪft/", meaning: "v. 转变；n. 轮班", example: "Public opinion has shifted significantly.", pos: "v" },
  { word: "significant", phonetic: "/sɪɡˈnɪfɪkənt/", meaning: "adj. 重要的；显著的", example: "There has been a significant improvement.", pos: "adj" },
  { word: "simulate", phonetic: "/ˈsɪmjuleɪt/", meaning: "v. 模拟；仿真", example: "The software can simulate real-world conditions.", pos: "v" },
  { word: "source", phonetic: "/sɔːrs/", meaning: "n. 来源；根源", example: "What is the source of this information?", pos: "n" },
  { word: "specific", phonetic: "/spəˈsɪfɪk/", meaning: "adj. 具体的；特定的", example: "Can you be more specific about your plans?", pos: "adj" },
  { word: "stable", phonetic: "/ˈsteɪbl/", meaning: "adj. 稳定的；稳固的", example: "The situation is now relatively stable.", pos: "adj" },
  { word: "strategy", phonetic: "/ˈstrætədʒi/", meaning: "n. 策略；战略", example: "We need a clear strategy for growth.", pos: "n" },
  { word: "structure", phonetic: "/ˈstrʌktʃər/", meaning: "n. 结构；构造", example: "The organizational structure needs to change.", pos: "n" },
  { word: "subsequent", phonetic: "/ˈsʌbsɪkwənt/", meaning: "adj. 随后的；后来的", example: "Subsequent events proved her right.", pos: "adj" },
  { word: "sufficient", phonetic: "/səˈfɪʃnt/", meaning: "adj. 足够的；充分的", example: "Is the evidence sufficient to proceed?", pos: "adj" },
  { word: "sustain", phonetic: "/səˈsteɪn/", meaning: "v. 维持；支撑", example: "The economy cannot sustain this level of growth.", pos: "v" },
  { word: "temporary", phonetic: "/ˈtempərəri/", meaning: "adj. 暂时的；临时的", example: "This is only a temporary solution.", pos: "adj" },
  { word: "terminate", phonetic: "/ˈtɜːrmɪneɪt/", meaning: "v. 终止；结束", example: "The contract was terminated early.", pos: "v" },
  { word: "transform", phonetic: "/trænsˈfɔːrm/", meaning: "v. 转变；变革", example: "Technology has transformed the way we work.", pos: "v" },
  { word: "trigger", phonetic: "/ˈtrɪɡər/", meaning: "v. 触发；引起", example: "Stress can trigger various health problems.", pos: "v" },
  { word: "ultimate", phonetic: "/ˈʌltɪmət/", meaning: "adj. 最终的；根本的", example: "Our ultimate goal is customer satisfaction.", pos: "adj" },
  { word: "undergo", phonetic: "/ˌʌndərˈɡəʊ/", meaning: "v. 经历；承受", example: "The building underwent major renovations.", pos: "v" },
  { word: "undertake", phonetic: "/ˌʌndərˈteɪk/", meaning: "v. 承担；从事", example: "She undertook a comprehensive review.", pos: "v" },
  { word: "valid", phonetic: "/ˈvælɪd/", meaning: "adj. 有效的；合理的", example: "Your passport must be valid for travel.", pos: "adj" },
  { word: "variable", phonetic: "/ˈveəriəbl/", meaning: "n. 变量；adj. 可变的", example: "There are too many variables to consider.", pos: "n" },
  { word: "verify", phonetic: "/ˈverɪfaɪ/", meaning: "v. 核实；验证", example: "Please verify your email address.", pos: "v" },
  { word: "via", phonetic: "/ˈvaɪə/", meaning: "prep. 通过；经由", example: "You can contact us via email.", pos: "prep" },
  { word: "visual", phonetic: "/ˈvɪʒuəl/", meaning: "adj. 视觉的；可视的", example: "Visual aids help with learning.", pos: "adj" },
  { word: "volume", phonetic: "/ˈvɒljuːm/", meaning: "n. 量；体积；音量", example: "The volume of traffic has increased.", pos: "n" },
  { word: "voluntary", phonetic: "/ˈvɒləntri/", meaning: "adj. 自愿的；志愿的", example: "Participation is entirely voluntary.", pos: "adj" },
  { word: "whereas", phonetic: "/weərˈæz/", meaning: "conj. 然而；而", example: "He likes coffee, whereas she prefers tea.", pos: "conj" },
  { word: "widespread", phonetic: "/ˈwaɪdspred/", meaning: "adj. 广泛的；普遍的", example: "There is widespread support for the policy.", pos: "adj" },
  { word: "worm", phonetic: "/wɜːrm/", meaning: "n. 蠕虫；v. 蠕动", example: "Birds feed on worms.", pos: "n" },
  { word: "yield", phonetic: "/jiːld/", meaning: "v. 产生；屈服；n. 产量", example: "The investment yielded good returns.", pos: "v" },
]
